### ISSUE TITLE
Edit this page not working

### ISSUE THREAD

**Issue by MiteshShah** [wpveda/book#32]
Issue URL: http://wpveda.com/git/linux_commands.html
 When we click on EDIT THIS PAGE its redirect on wrong location

http://wpveda.com/git/undefined/git/linux_commands.md

Also expose outdated nginx version.

**Comment by rahul286** [comment]
Edit link fixed. :-)

Nginx version is outdated at CDN77.com level. There is nothing to worry about it as this is static site, directly hosted on CDN and all content is anyway open-source.
