### ISSUE TITLE
Toggle Chapters

### ISSUE THREAD

**Issue by manishsongirkar** [wpveda/book#44]
@rahul286 

Can we install "Toggle Chapters on GitBook" plugin on http://wpveda.com/ if there is not any compatibility issue.

Plugin URL: https://github.com/poojan/gitbook-plugin-toggle-chapters

**Comment by rahul286** [comment]
I already coded and integrated support for  - https://www.npmjs.com/package/gitbook-plugin-collapsible-menu

I wish I could have come across this earlier!

**Comment by rohankveer** [comment]
When we click on the chapter title it does not opens the sub menu.

**Comment by nitun** [comment]
@rohankveer 
its working for me. 
Try `npm update` and check again.
