### ISSUE TITLE
Add vscode setup instructions

### ISSUE THREAD

**Issue by kirtangajjar** [wpveda/book#91]
vscode can also be used for WordPress Development. Add an entry [here](http://wpveda.com/meta/environment.html).

Mainly the page will contain links to specific plugins like 

- php-intelephense
- eslint
- phpcs
- php cs fixer
- PHP Debug(XDebug)
- WordPress Snippet

and other setup instructions(if any)

**Comment by chandrapatel** [comment]
@kirtangajjar Would you like to review https://github.com/wpveda/book/pull/99?
